### ISSUE TITLE
packet-journey fails to build with dpdk-2.2.0 due to deprecated warning as error

### ISSUE THREAD

**Issue by guerby** [Gandi/packet-journey#20]
```
  CC cmdline_helpers.o
/root/packet-journey/app/cmdline_helpers.c: In function ‘nic_stats_display’:
/root/packet-journey/app/cmdline_helpers.c:327:7: error: ‘ibadcrc’ is deprecated (declared at /root/dpdk-2.2.0/x86_64-native-linuxapp-gcc/include/rte_ethdev.h:203) [-Werror=deprecated-declarations]
       stats.ibadcrc, stats.ibadlen, stats.rx_nombuf,
       ^
/root/packet-journey/app/cmdline_helpers.c:327:7: error: ‘ibadlen’ is deprecated (declared at /root/dpdk-2.2.0/x86_64-native-linuxapp-gcc/include/rte_ethdev.h:205) [-Werror=deprecated-declarations]
/root/packet-journey/app/cmdline_helpers.c:328:7: error: ‘rx_pause_xon’ is deprecated (declared at /root/dpdk-2.2.0/x86_64-native-linuxapp-gcc/include/rte_ethdev.h:218) [-Werror=deprecated-declarations]
       stats.rx_pause_xon, stats.rx_pause_xoff, stats.opackets,
       ^
/root/packet-journey/app/cmdline_helpers.c:328:7: error: ‘rx_pause_xoff’ is deprecated (declared at /root/dpdk-2.2.0/x86_64-native-linuxapp-gcc/include/rte_ethdev.h:222) [-Werror=deprecated-declarations]
/root/packet-journey/app/cmdline_helpers.c:329:7: error: ‘tx_pause_xon’ is deprecated (declared at /root/dpdk-2.2.0/x86_64-native-linuxapp-gcc/include/rte_ethdev.h:216) [-Werror=deprecated-declarations]
       stats.oerrors, stats.obytes, stats.tx_pause_xon,
       ^
/root/packet-journey/app/cmdline_helpers.c:330:7: error: ‘tx_pause_xoff’ is deprecated (declared at /root/dpdk-2.2.0/x86_64-native-linuxapp-gcc/include/rte_ethdev.h:220) [-Werror=deprecated-declarations]
       stats.tx_pause_xoff);
       ^
/root/packet-journey/app/cmdline_helpers.c:363:11: error: ‘ibadcrc’ is deprecated (declared at /root/dpdk-2.2.0/x86_64-native-linuxapp-gcc/include/rte_ethdev.h:203) [-Werror=deprecated-declarations]
           stats.ibadcrc, stats.ibadlen, stats.ierrors);
           ^
/root/packet-journey/app/cmdline_helpers.c:363:11: error: ‘ibadlen’ is deprecated (declared at /root/dpdk-2.2.0/x86_64-native-linuxapp-gcc/include/rte_ethdev.h:205) [-Werror=deprecated-declarations]
/root/packet-journey/app/cmdline_helpers.c:391:3: error: ‘tx_pause_xon’ is deprecated (declared at /root/dpdk-2.2.0/x86_64-native-linuxapp-gcc/include/rte_ethdev.h:216) [-Werror=deprecated-declarations]
   if ((stats.tx_pause_xon | stats.rx_pause_xon |
   ^
/root/packet-journey/app/cmdline_helpers.c:391:3: error: ‘rx_pause_xon’ is deprecated (declared at /root/dpdk-2.2.0/x86_64-native-linuxapp-gcc/include/rte_ethdev.h:218) [-Werror=deprecated-declarations]
/root/packet-journey/app/cmdline_helpers.c:392:8: error: ‘tx_pause_xoff’ is deprecated (declared at /root/dpdk-2.2.0/x86_64-native-linuxapp-gcc/include/rte_ethdev.h:220) [-Werror=deprecated-declarations]
        stats.tx_pause_xoff | stats.rx_pause_xoff) > 0) {
        ^
/root/packet-journey/app/cmdline_helpers.c:392:8: error: ‘rx_pause_xoff’ is deprecated (declared at /root/dpdk-2.2.0/x86_64-native-linuxapp-gcc/include/rte_ethdev.h:222) [-Werror=deprecated-declarations]
/root/packet-journey/app/cmdline_helpers.c:395:12: error: ‘rx_pause_xoff’ is deprecated (declared at /root/dpdk-2.2.0/x86_64-native-linuxapp-gcc/include/rte_ethdev.h:222) [-Werror=deprecated-declarations]
            stats.rx_pause_xoff, stats.rx_pause_xon);
            ^
/root/packet-journey/app/cmdline_helpers.c:395:12: error: ‘rx_pause_xon’ is deprecated (declared at /root/dpdk-2.2.0/x86_64-native-linuxapp-gcc/include/rte_ethdev.h:218) [-Werror=deprecated-declarations]
/root/packet-journey/app/cmdline_helpers.c:398:12: error: ‘tx_pause_xoff’ is deprecated (declared at /root/dpdk-2.2.0/x86_64-native-linuxapp-gcc/include/rte_ethdev.h:220) [-Werror=deprecated-declarations]
            stats.tx_pause_xoff, stats.tx_pause_xon);
            ^
/root/packet-journey/app/cmdline_helpers.c:398:12: error: ‘tx_pause_xon’ is deprecated (declared at /root/dpdk-2.2.0/x86_64-native-linuxapp-gcc/include/rte_ethdev.h:216) [-Werror=deprecated-declarations]
cc1: all warnings being treated as errors
make[2]: *** [cmdline_helpers.o] Error 1
make[1]: *** [all] Error 2
make: *** [app] Error 2
```

**Comment by guerby** [comment]
I applied the following workaround patch to dpdk-2.2.0 to be able to compile packet-journey:
````
--- lib/librte_eal/common/include/rte_common.h.orig	2015-12-23 19:48:31.344800031 +0100
+++ lib/librte_eal/common/include/rte_common.h	2015-12-23 19:41:50.560791024 +0100
@@ -80,7 +80,8 @@
 #define __rte_packed __attribute__((__packed__))
 
 /******* Macro to mark functions and fields scheduled for removal *****/
-#define __rte_deprecated	__attribute__((__deprecated__))
+/* #define __rte_deprecated	__attribute__((__deprecated__)) */
+#define __rte_deprecated	
 
 /*********** Macros to eliminate unused variable warnings ********/
 
````

**Comment by klnikita** [comment]
I have prepared the pull request #22 for removing those stats.
I must test it a little bit before merging, especially the SNMP export part.

**Comment by klnikita** [comment]
Fixed since switched to DPDK 2.2.0
