### ISSUE TITLE
DPDK minimal version

### ISSUE THREAD

**Issue by tarelda** [Gandi/packet-journey#44]
What is maximal and minimal DPDK version for packetjourney to compile?

**Comment by fatih-acar** [comment]
Packet-journey should compile using DPDK versions from 1.8 up to 18.08.
I've pushed commit 35cceb7d which adds support for 18.08.

**Comment by tarelda** [comment]
I started with 2.0 and found success starting with 18.02. My approach consisted of trying to find the first commit fixing thing that compiler was complaining about and then picking up the first stable version that implemented it.

**Comment by tarelda** [comment]
@fatih-acar I just realised that my repository was lagging one commit behind current master. So I fast forwarded it to HEAD and tried to compile pktj against DPDK 18.08.1 and suprisingly it didn't work. 

`
== lib
== libneighbour
  SYMLINK-FILE include/libneighbour.h
  CC neighbour.o
  AR libneighbour.a
  INSTALL-LIB libneighbour.a
== libnetlink
  SYMLINK-FILE include/libnetlink.h
  CC netlink.o
  AR libnetlink.a
  INSTALL-LIB libnetlink.a
== app
  CC main.o
/root/packet-journey/app/main.c: In function ‘init_port’:
/root/packet-journey/app/main.c:1902:8: error: ‘struct rte_eth_txconf’ has no member named ‘txq_flags’
  txconf->txq_flags &= ~ETH_TXQ_FLAGS_NOOFFLOADS;
        ^
/root/packet-journey/app/main.c:1902:24: error: ‘ETH_TXQ_FLAGS_NOOFFLOADS’ undeclared (first use in this function)
  txconf->txq_flags &= ~ETH_TXQ_FLAGS_NOOFFLOADS;
                        ^
/root/packet-journey/app/main.c:1902:24: note: each undeclared identifier is reported only once for each function it appears in
/root/packet-journey/app/main.c:1906:22: error: ‘struct rte_eth_rxmode’ has no member named ‘jumbo_frame’
  if (port_conf.rxmode.jumbo_frame)
                      ^
/root/packet-journey/app/main.c:1907:9: error: ‘struct rte_eth_txconf’ has no member named ‘txq_flags’
   txconf->txq_flags = 0;
         ^
/root/packet-journey/app/main.c:1979:9: error: ‘struct rte_eth_txconf’ has no member named ‘txq_flags’
   txconf->txq_flags &= ~ETH_TXQ_FLAGS_NOOFFLOADS;
         ^
/root/packet-journey/app/main.c:1983:23: error: ‘struct rte_eth_rxmode’ has no member named ‘jumbo_frame’
   if (port_conf.rxmode.jumbo_frame)
                       ^
/root/packet-journey/app/main.c:1984:10: error: ‘struct rte_eth_txconf’ has no member named ‘txq_flags’
    txconf->txq_flags = 0;
          ^
/root/dpdk/mk/internal/rte.compile-pre.mk:114: recipe for target 'main.o' failed
make[2]: *** [main.o] Error 1
/root/dpdk/mk/rte.extapp.mk:14: recipe for target 'all' failed
make[1]: *** [all] Error 2
/root/dpdk/mk/rte.extsubdir.mk:21: recipe for target 'app' failed
make: *** [app] Error 2
`

What is more, I tried to compile this codebase against previously working 18.02 and it also failed.
